export default {
  'Abate': 'v. to become less active, less intense, or less in amount',
  'Abstract': 'adj. existing purely in the mind; not representing actual reality',
  'Abysmal': 'adj. extremely bad',
  'Accordingly': 'adv. in accordance with',
  'Acquisition': 'n. the act of gaining a skill or possession of something',
  'Adapt': 'v. to make suit a new purpose',
  'Adept': 'adj. having knowledge or skill (usu. in a particular area)',
  'Adequate': 'adj. having sufficient qualifications to meet a specific task or purpose',
  'Advent': 'n. the arrival or creation of something (usu. historic)',
  'Adversarial': 'adj. relating to hostile opposition',
  'Advocate': 'n. someone who promotes or defends something',
  'Aesthetic': 'adj. relating to beauty or refined taste',
  'Afford': 'v. to be able to buy',
  'Agitate': 'v. to promote something (usu. a cause)',
  'Allow': 'v. to permit or consent to',
  'Allude': 'v. to make a secretive mention of something',
  'Altercation': 'n. a noisy argument or confrontation',
  'Ambiguous': 'adj. unclear or vague in meaning',
  'Ambitious': 'adj. having a powerful desire for success or achievement',
  'Ambivalence': 'n. the state of being uncertain or stuck between two or more options',
  'Analogous': 'adj. similar but not identical',
  'Annihilate': 'v. to destroy or cause devastating destruction',
  'Anomaly': 'n. something different from the norm',
  'Anticipate': 'v. assume to be likely to happen',
  'Antipathy': 'n. a strong feeling of dislike',
  'Apex': 'n. the highest point of something',
  'Apprehension': 'n. fearful expectation of something',
  'Articulate': 'v. to clearly express in words',
  'Artificial': 'adj. something made; not occurring naturally',
  'Assertion': 'n. a strong declaration',
  'Austere': 'adj. extremely plain',
  'Authenticity': 'n. the quality of being real and true instead of fake and contrived',
  'Avenue': 'n. an intangible path or approach to something',
  'Avid': 'adj. actively interested in or enthusiastic about something',
  'Basic': 'adj. relating to the foundation or basis of something',
  'Bear': 'v. to have as a characteristic',
  'Benevolent': 'adj. kind, generous',
  'Bias': 'n. a preconception that prevents objectivity',
  'Bittersweet': 'adj. tinged with a feeling of sadness',
  'Bolster': 'v. to support, strengthen, or fortify',
  'Boost': 'n. an increase or growth',
  'Brawl': 'n. an intense, loud fight',
  'Brevity': 'n. the quality of being brief or terse',
  'Candid': 'adj. direct, blunt',
  'Candor': 'n. the trait of being honest and frank',
  'Capitalize': 'v. to use to your advantage',
  'Capture': 'v. to trap or take possession of',
  'Civic': 'adj. relating to the city or citizens',
  'Clinical': 'adj. emotionally unattached (usu. used in medical or scientific setting)',
  'Clout': 'n. special advantage or power',
  'Coarse': 'adj. indicating a rough texture',
  'Coincide': 'v. to happen at the same time',
  'Commission': 'n. the use of payment to request something (e.g., a service or product)',
  'Comparable': 'adj. able to be compared',
  'Competent': 'adj. sufficiently qualified',
  'Complacent': 'adj. satisfied, with no desire to change or improve',
  'Complement': 'v. to make perfect or complete',
  'Concede': 'v. to be forced to agree or surrender',
  'Conceive': 'v. to imagine or come up with',
  'Condone': 'v. to overlook, approve, or allow',
  'Conducive': 'adj. able to bring about or be suitable for',
  'Conduct': 'v. to control or manage',
  'Confide': 'v. to share something secretive with someone',
  'Confine': 'v. to put limits on; to restrict',
  'Consensus': 'n. overall agreement',
  'Constitute': 'v. to form or compose (part of) something',
  'Contemplate': 'v. to think deeply about',
  'Contend': 'v. to maintain or assert (an opinion)',
  'Contradict': 'v. to be in contrast with',
  'Controversial': 'adj. highly debatable and causing contention',
  'Conventional': 'adj. abiding by accepted standards',
  'Convey': 'v. to pass on or transfer (information)',
  'Conviction': 'n. a firm belief in something',
  'Corroborate': 'v. to provide evidence for; to back up (a claim)',
  'Counteract': 'v. to work in opposition to',
  'Counterargument': 'n. an argument used to criticize or dismantle another argument',
  'Counterproductive': 'adj. hindering the achievement of a goal',
  'Culmination': 'n. the final act or climax',
  'Cultivate': 'v. to foster the growth of',
  'Decree': 'v. to declare formally and with authority',
  'Deference': 'n. respect; regard',
  'Deficient': 'adj. not enough in degree or amount',
  'Demonstrate': 'v. to do as an example',
  'Demur': 'v. to object to',
  'Deplete': 'v. to (over)use over time (usu. resources)',
  'Desolate': 'adj. bare, barren, empty',
  'Devise': 'v. to come up with (a plan)',
  'Dilemma': 'n. a problem, usually requiring a choice between two options',
  'Diligence': 'n. conscientiousness; the quality of being committed to a task',
  'Diminish': 'v. to become smaller in scope or degree',
  'Dire': 'adj. hopeless and dangerous or fearful',
  'Discord': 'n. disagreement',
  'Disdain': 'n. a lack of respect and strong dislike (toward something or someone)',
  'Dismay': 'n. hopelessness, stress, or consternation',
  'Disparage': 'v. to belittle or speak down to',
  'Dispatch': 'v. to send off a message or messenger',
  'Diversification': 'n. the act of becoming diverse',
  'Doctrine': 'n. a principle, theory, or position, usu. advocated by a religion or gov’t',
  'Dominion': 'n. power and authority (usu. over a territory)',
  'Dreary': 'adj. sad, gloomy, dull',
  'Dubious': 'adj. doubtful, questionable',
  'Eccentric': 'adj. peculiar or odd; deviating from the norm',
  'Egregious': 'adj. extremely bad',
  'Eloquent': 'adj. having refined or expressive communication skills (in speaking or writing)',
  'Eminent': 'adj. superior or distinguished; high in position or status',
  'Emit': 'v. to discharge, give forth, or release',
  'Emphatic': 'adj. very expressive; using emphasis',
  'Empirical': 'adj. derived from experience, observation, or an experiment',
  'Endow': 'v. to equip or bestow (usu. a quality or ability)',
  'Endure': 'v. to withstand, sustain, or hold out against',
  'Entail': 'v. to involve or include',
  'Entrenched': 'adj. firmly established',
  'Enumerate': 'v. to specify or count',
  'Envy': 'n. excessive jealousy',
  'Erratic': 'adj. having no fixed course; deviating from the norm',
  'Establish': 'v. to enact',
  'Evoke': 'v. to draw forth or call up',
  'Exacerbate': 'v. to make worse or increase the severity of',
  'Excel': 'v. to do something extremely well or to be superior in',
  'Exert': 'v. to put into use (usu. as effort)',
  'Exhilarating': 'adj. invigorating, stimulating, or exciting',
  'Expend': 'v. to use up (as in energy or money)',
  'Exploit': 'v. to use selfishly or for profit',
  'Facilitate': 'v. to aid the progress of',
  'Feasibility': 'n. the practicality or possibility of something',
  'Ferocity': 'n. viciousness, violence',
  'Fiscal': 'adj. related to (government) money',
  'Flourish': 'v. to prosper, grow, or make fast progress',
  'Fluctuate': 'v. to be unstable; to rise and fall',
  'Foment': 'v. to stir up',
  'Foreseeable': 'adj. capable of being predicted or anticipated',
  'Frankly': 'adv. directly, clearly',
  'Freewheeling': 'adj. carefree',
  'Fundamental': 'adj. the most essential or most basic part',
  'Galvanizing': 'adj. thrilling, exciting, stimulating',
  'Geriatric': 'adj. relating to old age',
  'Hostile': 'adj. harmful, dangerous',
  'Hypothetical': 'adj. supposed; related to a hypothesis',
  'Ignominious': 'adj. publicly shameful or humiliating',
  'Impart': 'v. to transmit, bestow, or disclose',
  'Impartiality': 'n. the equal and objective treatment of opposing views',
  'Imposing': 'adj. impressive (esp. in size or appearance)',
  'Imposition': 'n. an unnecessary burden',
  'Imprudent': 'adj. not cautious or prudent; rash',
  'Incite': 'v. to encourage or stir up',
  'Indifference': 'n. apathy, emotional detachment',
  'Indiscriminately': 'adv. randomly; with little or no distinction',
  'Indulge': 'v. to give into; to satisfy or gratify',
  'Infer': 'v. to guess, conclude, or derive by reasoning',
  'Innovative': 'adj. novel or new (esp. as an idea or invention)',
  'Insatiable': 'adj. can’t be satisfied',
  'Inversion': 'n. a reversal',
  'Invoke': 'v. to call on; to appeal to (e.g., a higher power)',
  'Irreconcilable': 'adj. incapable of being in harmony or agreed upon',
  'Lucrative': 'adj. capable of making a lot of money; profitable',
  'Malicious': 'adj. harmful, spiteful',
  'Malleable': 'adj. capable of being molded or changed',
  'Materialistic': 'adj. superficial; focus on material possessions',
  'Melodramatic': 'adj. extravagant or exaggerated (as of a melodrama)',
  'Modest': 'adj. simple and humble',
  'Modify': 'v. to change, alter, or tweak',
  'Momentous': 'adj. historically significant',
  'Novel': 'adj. new, innovative',
  'Nuance': 'n. a subtle difference in meaning',
  'Null': 'adj. legally void and ineffective',
  'Objectivity': 'n. judgment based on observations instead of emotions or opinions',
  'Obsolete': 'adj. no longer used; rare or uncommon',
  'Omnipotent': 'adj. almighty and all powerful',
  'Onset': 'n. the beginning or early stages',
  'Opine': 'v. to openly express an opinion',
  'Ornate': 'adj. highly detailed and decorated',
  'Oust': 'v. to remove or force out of (usu. a position or office)',
  'Paramount': 'adj. predominant, superior, most important',
  'Peculiar': 'adj. strange, bizarre',
  'Perish': 'v. to die; to pass away',
  'Persecute': 'v. to cause suffering to',
  'Petulant': 'adj. cranky, pouty, irritable',
  'Pinnacle': 'n. highest level or degree',
  'Pitiable': 'adj. deserving pity',
  'Plausible': 'adj. reasonable and possibly true',
  'Postulate': 'v. to assert',
  'Potent': 'adj. having great influence',
  'Pragmatic': 'adj. practical, useful',
  'Precedent': 'n. an example or subject from earlier in time',
  'Predecessor': 'n.  someone who comes before you (usu. in position or office)',
  'Prescribe': 'v. to command orders',
  'Principle': 'n. basic truth, assumption, or rule',
  'Prohibit': 'v. to command against, to outlaw',
  'Prompt': 'adj. punctual, on time',
  'Promulgate': 'v. to put into law or formally declare',
  'Prosecute': 'v. to bring criminal action against someone (in a trial)',
  'Provocative': 'adj. intending to provoke, inspire, or arouse',
  'Qualitative': 'adj. involving qualities of something (features and content)',
  'Quantitative': 'adj. involving quantities (numbers and amounts)',
  'Quirk': 'n. a strange habit',
  'Ramify': 'v. to split into two or more branches',
  'Rash': 'adj. without attention to danger or risk',
  'Raw': 'adj. unrefined',
  'Readily': 'adv. right away and without difficulty',
  'Reconsideration': 'n. thinking again about a previously made choice',
  'Reform': 'n. a change for the better; improvement',
  'Refute': 'v. to prove to be untrue, unfounded, or incorrect',
  'Reinforce': 'v. to strengthen or add support to',
  'Reluctantly': 'adv. somewhat unwillingly',
  'Renounce': 'v. to give up (usu. power or a position)',
  'Reproach': 'v. to criticize',
  'Repudiate': 'v. to refuse to recognize as true',
  'Retention': 'n. the act of keeping something',
  'Satiated': 'adj. satisfied (usu. in hunger)',
  'Savvy': 'adj. having practical intelligence or knowledge',
  'Scandalous': 'adj. morally offensive, often causing damage to one’s reputation',
  'Scorn': 'v. to look down on with disdain',
  'Scrupulous': 'adj. paying great attention to detail',
  'Scrutinize': 'v. to examine carefully and critically',
  'Secrete': 'v. to produce or release (a substance)',
  'Sentiment': 'n. opinion',
  'Sheer': 'adj. so thin that light can shine through',
  'Simple': 'adj. easy; not complex',
  'Sinister': 'adj. ominous, evil',
  'Solidarity': 'n. the joining of commonalities or common purposes among a group',
  'Sparingly': 'adv. insufficiently, meagerly, or in a restricted manner',
  'Spawn': 'v. to release eggs',
  'Spur': 'v. to stimulate or incite',
  'Squalid': 'adj. run-down, sordid, or sleazy',
  'Stark': 'adj. very plain; devoid of any details or features',
  'Static': 'adj. motionless',
  'Subordinate': 'adj. lower in rank',
  'Subsequently': 'adv. happening later or after something',
  'Substantial': 'adj. very large in amount or degree',
  'Substantiate': 'v. to strengthen with new evidence or facts',
  'Subtle': 'adj. hard to detect or analyze',
  'Sufficient': 'adj. enough; just meeting a requirement',
  'Surly': 'adj. unfriendly; inclined to anger',
  'Surmount': 'v. to get on top of or overcome',
  'Susceptible': 'adj. to be vulnerable (to something)',
  'Tactful': 'adj. skilled at dealing with people',
  'Taut': 'adj. pulled tight',
  'Teeming': 'adj. abundantly filled (usu. with living organisms)',
  'Temperament': 'n. usual mood or feelings',
  'Tentative': 'adj. not yet finalized',
  'Transparent': 'adj. see-through; so thin that light can shine through',
  'Treacherous': 'adj. dangerous and unstable',
  'Tremendous': 'adj. very large, good, or bad in degree or size',
  'Ubiquitous': 'adj. being everywhere at once',
  'Unadorned': 'adj. undecorated, plain',
  'Undermine': 'v. to weaken or subvert (usu. gradually or secretly)',
  'Underscore': 'v. to emphasize or give additional weight to',
  'Undulate': 'v. to move as ripples or in a wavy pattern',
  'Unilateral': 'adj. one-sided',
  'Unjust': 'adj. unfair; not justified',
  'Unmitigated': 'adj. downright, utter, total',
  'Unprecedented': 'adj. completely new and never having happened before; historic',
  'Unveil': 'v. to make visible; to reveal',
  'Urge': 'n. desire or impulse',
  'Validate': 'v. to prove or declare valid',
  'Viability': 'n. ability to be done in a practical or useful way',
  'Vital': 'adj. urgently necessary',
  'Vow': 'v. to promise',
  'Warrant': 'v. to prove to be reasonable',
  'Yield': 'n. production of an amount'
};
