export default {
  'atom': 'the smallest component of an element',
  'asteroid': 'a small celestial body composed of rock and metal',
  'atmosphere': 'the envelope of gases surrounding any celestial body',
  'cell': 'the basic structural and functional unit of all organisms',
  'climate': 'the weather in some location averaged over a period of time',
  'comet': 'a small frozen mass that travels around the sun',
  'deceleration': 'a decrease in rate of change',
  'galaxy': 'a collection of star systems',
  'gene': 'part of DNA controlling physical characteristics and growth',
  'homeostasis': 'metabolic equilibrium maintained by biological mechanisms',
  'hypothesis': 'a tentative insight that is not yet verified or tested',
  'inertia': 'the tendency of something to stay in rest or motion',
  'kinetic': 'type of energy that a body has by virtue of motion',
  'digestive': 'the system that makes food absorbable into the body',
  'molecule': 'the simplest structural unit of an element or compound',
  'nuclear': 'type of reaction that alters the energy or structure or composition of atomic nuclei',
  'organ': 'a structure in an animal specialized for some function',
  'oxidation': 'the process by which a substance combines with oxygen',
  'parasite': 'an animal or plant that lives in or on a host',
  'photosynthesis': 'synthesis of compounds in plants aided by radiant energy',
  'radiation': 'the act of spreading outward from a central source',
  'respiration': 'a single complete act of breathing in and out',
  'rusting': 'the formation of reddish-brown ferric oxides on iron by low-temperature oxidation in the presence of water',
  'satellite': 'any celestial body orbiting around a planet or star',
  'speed': 'a rate at which something happens',
  'taxonomy': 'a classification of organisms based on similarities',
  'tissue': 'part of an organism consisting of an aggregate of cells',
  'vertebrate': 'animals having a bony or cartilaginous skeleton',
  'wavelength': 'a shared orientation leading to mutual understanding',
  'invertebrate': 'any animal lacking a backbone or notochord'

}
