export default {
  'ser': 'to be (personality, nationality, physical description, etc.)',
  'serio': 'serious',
  'deportista': 'sporty',
  'trabajador': 'hard-working',
  'paciente': 'patient',
  'joven': 'young',
  'alto': 'tall',
  'atrevido': 'daring',
  'bajo': 'short',
  'desordenado': 'messy',
  'estudioso': 'studious',
  'gracioso': 'funny',
  'feo': 'ugly',
  'guapo': 'good-looking',
  'impaciente': 'impatient',
  'inteligente': 'intelligent',
  'ordenado': 'neat',
  'reservado': 'shy',
  'sociable': 'social',
  'viejo': 'old',
  'soy': 'I am',
  'eres': 'you are',
  'es': 'he, she is, you (form.) are',
  'somos': 'we are',
  'sois': 'you (pl. fam.) are',
  'son': 'they, you (pl. form.) are'

}
